import { CausalCommandStory } from './types';
import { GitRepo } from '../../git-engine/types';

/**
 * Dynamic Causal Stories for 22 Git operations.
 * Adheres strictly to the 6-step causal framework:
 * START -> USER REQUEST -> GIT CHECKS -> GIT CHANGES -> ENDING STATE -> WHY IT MATTERS
 */

export function getCausalStory(commandId: string, repo?: GitRepo): CausalCommandStory {
  const currentBranch = repo?.head.type === 'branch' ? repo.head.ref : 'main';
  const headCommit = repo?.branches[currentBranch]?.targetCommitHash?.slice(0, 7) || 'a3f2e1d';

  const stories: Record<string, CausalCommandStory> = {
    // 1. GIT PUSH (Signature Implementation matching reference mockup)
    'push': {
      id: 'push',
      command: `git push origin ${currentBranch}`,
      title: 'Pushing to a Remote',
      category: 'remotes',
      subtitle: 'Send your local commits to a remote repository so others can see your work.',
      mentalModelQuote: 'Send your local saved versions to the shared remote repository.',
      keyTakeaways: [
        'git push sends your local commits and objects to a remote.',
        'It updates the remote branch pointer so others can see your work.',
        'You need network access and push permissions.',
        'If the remote has newer commits, Git rejects the push until you pull.',
      ],
      terminalDemo: {
        command: `git push origin ${currentBranch}`,
        outputLines: [
          'Enumerating objects: 5, done.',
          'Counting objects: 100% (5/5), done.',
          'Delta compression using up to 8 threads',
          'Compressing objects: 100% (3/3), done.',
          'Writing objects: 100% (3/3), 354 bytes | 354.00 KiB/s, done.',
          'Total 3 (delta 1), reused 0 (delta 0)',
          'To github.com:you/my-website.git',
          `   9b1c7a0..${headCommit}  ${currentBranch} -> ${currentBranch}`,
        ],
      },
      simulatorType: 'push',
      steps: [
        {
          id: 'push-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Starting State',
          description: 'Your local repository has commits that the remote repository does not yet possess.',
          simpleExplanation: 'You finished work on your computer. Your local repository has a new commit waiting to be shared.',
          technicalExplanation: `Local branch '${currentBranch}' points to ${headCommit}. Remote branch 'origin/${currentBranch}' is currently at parent 9b1c7a0.`,
          whatGitChecks: 'Git reads local repository configuration and verifies remote origin exists.',
          whatGitChanges: 'Nothing yet. Preparing to contact remote.',
          whatChangedBadges: ['Local Ahead by 1 commit'],
          whyDidGitDoThat: 'Git never automatically uploads in the background. It waits for you to explicitly run git push.',
        },
        {
          id: 'push-2-contact',
          label: '2. Contact',
          phase: 'request',
          title: 'Git Contacts Remote',
          description: 'Git establishes a network connection with the remote server (e.g. GitHub).',
          simpleExplanation: 'Git knocks on the remote server\'s door and checks if it can communicate.',
          technicalExplanation: 'Local Git opens an SSH or HTTPS connection to the remote repository URL specified in git remote -v.',
          whatGitChecks: 'Network connectivity and authentication credentials.',
          whatGitChanges: 'Handshake initiated; connection authenticated.',
          whatChangedBadges: ['Connected to origin'],
          whyDidGitDoThat: 'Git must verify credentials and remote address before requesting or sending data.',
        },
        {
          id: 'push-3-discover',
          label: '3. Discover',
          phase: 'check',
          title: 'Discover Remote State',
          description: 'The remote server advertises its current references and commit positions.',
          simpleExplanation: 'The remote tells your computer: "Here is where my branches currently point."',
          technicalExplanation: 'The remote advertises reference tips via protocol discovery: origin/main = 9b1c7a0.',
          whatGitChecks: 'Reads advertised refs from remote server.',
          whatGitChanges: 'Local Git stores the remote advertisement.',
          whatChangedBadges: ['Remote Tip: 9b1c7a0'],
          whyDidGitDoThat: 'Git cannot know what to send until it knows what the remote already has.',
        },
        {
          id: 'push-4-compare',
          label: '4. Compare',
          phase: 'check',
          title: 'Compare Histories',
          description: 'Git compares local commit graph against remote commit graph.',
          simpleExplanation: 'Git discovers that the remote already has C1 and C2, but is missing C3.',
          technicalExplanation: `Git finds the common ancestor (9b1c7a0). It validates that local ${headCommit} is a direct descendant (fast-forward safe).`,
          whatGitChecks: 'Is local branch an ancestor or fast-forward of remote branch?',
          whatGitChanges: 'Identifies missing object set: commit C3, tree, and modified file blobs.',
          whatChangedBadges: ['Missing: C3'],
          whyDidGitDoThat: 'By comparing histories, Git avoids re-sending commits that the server already holds, making push fast and efficient.',
          prediction: {
            prompt: 'When you push, what will happen to the remote branch reference (origin/main)?',
            options: [
              'It will advance forward to match your local commit (C3)',
              'It will delete your local commit to match the server',
              'The remote will create a duplicate copy of the entire project folder',
              '🤔 I\'m not sure',
            ],
            correctIndex: 0,
            hint: 'A push asks the remote branch pointer to advance to your latest commit.',
            explanation: 'When Git sends C3, the remote branch reference moves forward from C2 to C3. Both repositories will now be in sync!',
          },
        },
        {
          id: 'push-5-prepare',
          label: '5. Prepare',
          phase: 'decide',
          title: 'Prepare Required Data',
          description: 'Git bundles only the missing commits and objects into a compressed packet.',
          simpleExplanation: 'Git prepares the package of saved changes needed by the remote.',
          technicalExplanation: 'Git generates a packfile containing only reachable objects in local that are not on remote.',
          whatGitChecks: 'Computes delta compression and object dependencies.',
          whatGitChanges: 'Packfile assembled in memory.',
          whatChangedBadges: ['Packfile: 354 bytes'],
          whyDidGitDoThat: 'Git pushes commits and object graphs—it does NOT re-upload unchanged files.',
        },
        {
          id: 'push-6-transfer',
          label: '6. Transfer',
          phase: 'change',
          title: 'Transfer Over Network',
          description: 'The packed objects stream across the internet to the remote repository.',
          simpleExplanation: 'The data packets travel from your computer into the GitHub cloud.',
          technicalExplanation: 'Objects written to remote socket. Remote unpacks and verifies object database integrity.',
          whatGitChecks: 'Verifies checksums and transmission parity.',
          whatGitChanges: 'Remote writes new objects into its .git/objects store.',
          whatChangedBadges: ['Objects Transferred'],
          whyDidGitDoThat: 'The remote must store the new objects before it can safely move its branch pointers.',
        },
        {
          id: 'push-7-update',
          label: '7. Update',
          phase: 'change',
          title: 'Remote & Tracking Branches Advance',
          description: 'The remote moves its branch pointer, and your local remote-tracking branch updates.',
          simpleExplanation: 'The remote updates its branch label to point to your new commit!',
          technicalExplanation: `Remote updates refs/heads/${currentBranch} -> ${headCommit}. Local updates refs/remotes/origin/${currentBranch} -> ${headCommit}.`,
          whatGitChecks: 'Ref update accepted by remote reference lock.',
          whatGitChanges: `origin/${currentBranch} moves from 9b1c7a0 to ${headCommit}.`,
          whatChangedBadges: [`origin/${currentBranch} -> ${headCommit}`],
          whyDidGitDoThat: 'Branch pointers are movable labels. When the commit lands safely, the label moves forward.',
        },
        {
          id: 'push-8-complete',
          label: '8. Complete',
          phase: 'complete',
          title: 'In Sync ✓',
          description: 'Both your local repository and the remote repository are completely synchronized.',
          simpleExplanation: 'Your commits are now safe in the cloud. Teammates can pull and see your work!',
          technicalExplanation: `Local ${currentBranch} and remote-tracking origin/${currentBranch} now point to the identical commit hash ${headCommit}.`,
          whatGitChecks: 'Everything matches.',
          whatGitChanges: 'Synchronization state confirmed.',
          whatChangedBadges: ['✓ In Sync'],
          whyDidGitDoThat: 'You have shared your historical snapshot with the world!',
        },
      ],
    },

    // 2. GIT COMMIT (Signature Implementation 2)
    'commit': {
      id: 'commit',
      command: 'git commit -m "Update homepage"',
      title: 'Creating a Commit',
      category: 'foundations',
      subtitle: 'Seal everything in the staging area into a permanent historical snapshot.',
      mentalModelQuote: 'Take a permanent photo of what you placed in the staging box.',
      keyTakeaways: [
        'A commit is a permanent snapshot of staged files.',
        'It has an author, timestamp, unique object hash, and points to its parent.',
        'Running commit empties the staging area for your next task.',
        'Your working files remain safely on your desk.',
      ],
      terminalDemo: {
        command: 'git commit -m "Update homepage"',
        outputLines: [
          `[${currentBranch} ${headCommit}] Update homepage`,
          ' 1 file changed, 4 insertions(+), 1 deletion(-)',
        ],
      },
      simulatorType: 'commit',
      steps: [
        {
          id: 'commit-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Staged Changes Ready',
          description: 'You have modified files and placed them in the staging area with git add.',
          simpleExplanation: 'Your desk has your project files, and your packing box has staged changes.',
          technicalExplanation: 'The Git index (.git/index) contains staged blob hashes ready to be committed.',
          whatGitChecks: 'Inspects index to see if changes are staged.',
          whatGitChanges: 'Nothing yet.',
          whatChangedBadges: ['1 file staged in index'],
          whyDidGitDoThat: 'Git never commits unstaged working files by default.',
        },
        {
          id: 'commit-2-check-index',
          label: '2. Check Index',
          phase: 'check',
          title: 'Git Validates Staging Area',
          description: 'Git verifies that the index contains changes compared to the parent commit.',
          simpleExplanation: 'Git checks: "Is there anything in the packing box to save?"',
          technicalExplanation: 'Git compares index tree against HEAD commit tree. If identical, returns "nothing to commit".',
          whatGitChecks: 'Is index != HEAD?',
          whatGitChanges: 'Validation passes.',
          whatChangedBadges: ['Staging validated'],
          whyDidGitDoThat: 'Git prevents creating empty, redundant commits without explicit flags.',
          prediction: {
            prompt: 'When git commit runs, what happens to the files currently in the Staging Area?',
            options: [
              'They are sealed into a new commit, and the staging area clears',
              'They are permanently deleted from your computer',
              'They move to GitHub immediately',
              '🤔 I\'m not sure',
            ],
            correctIndex: 0,
            hint: 'The packing box gets sealed into a permanent snapshot and emptied for your next task.',
            explanation: 'The staging area is cleared because its contents have now been safely recorded in the new commit!',
          },
        },
        {
          id: 'commit-3-create-tree',
          label: '3. Create Tree',
          phase: 'change',
          title: 'Snapshot Compressed',
          description: 'Git writes a tree object representing directory structure and file contents.',
          simpleExplanation: 'Git creates an exact digital record of the files in your project right now.',
          technicalExplanation: 'Git writes tree object to .git/objects containing mode, type, blob hash, and filenames.',
          whatGitChecks: 'Blob existence in object database.',
          whatGitChanges: 'Tree object written with unique hash.',
          whatChangedBadges: ['Tree Object Created'],
          whyDidGitDoThat: 'Git stores directories as trees and files as blobs.',
        },
        {
          id: 'commit-4-create-commit',
          label: '4. Seal Commit',
          phase: 'change',
          title: 'New Commit Object Sealed',
          description: 'Git creates the commit object with author, date, message, tree hash, and parent hash.',
          simpleExplanation: '📸 Snap! A brand new commit node appears in your project history.',
          technicalExplanation: `Commit object created with parent pointer to previous HEAD and tree reference.`,
          whatGitChecks: 'Parent commit hash.',
          whatGitChanges: `New commit node ${headCommit} created.`,
          whatChangedBadges: [`Commit ${headCommit}`],
          whyDidGitDoThat: 'Commits are immutable snapshots linked into an acyclic graph of project history.',
        },
        {
          id: 'commit-5-move-branch',
          label: '5. Advance Branch',
          phase: 'change',
          title: 'Branch & HEAD Labels Advance',
          description: 'Your current branch pointer moves to point to the new commit.',
          simpleExplanation: 'The branch label moves forward so it points to your newest commit.',
          technicalExplanation: `refs/heads/${currentBranch} updated to ${headCommit}. HEAD continues pointing symbolically to ${currentBranch}.`,
          whatGitChecks: 'Current active branch.',
          whatGitChanges: `${currentBranch} moves forward; HEAD follows.`,
          whatChangedBadges: [`${currentBranch} -> ${headCommit}`],
          whyDidGitDoThat: 'Branches are movable references. Creating a commit automatically moves the active branch forward.',
        },
        {
          id: 'commit-6-complete',
          label: '6. Complete',
          phase: 'complete',
          title: 'Snapshot Saved ✓',
          description: 'Staging box is emptied and ready for your next feature. Your work is permanently safe.',
          simpleExplanation: 'You just saved a permanent version. You can now undo, branch, or share this work safely.',
          technicalExplanation: 'Working directory clean relative to HEAD. Staging area clean. History updated.',
          whatGitChecks: 'Repository state clean.',
          whatGitChanges: 'Staging box reset.',
          whatChangedBadges: ['✓ Clean State'],
          whyDidGitDoThat: 'The staging area is now ready for your next logical change.',
        },
      ],
    },

    // 3. GIT ADD
    'add': {
      id: 'add',
      command: 'git add index.html',
      title: 'Staging with git add',
      category: 'foundations',
      subtitle: 'Selectively place modified files into the staging box before committing.',
      mentalModelQuote: 'Choose which changes belong in your next snapshot.',
      keyTakeaways: [
        'git add moves files from the Working Tree into the Staging Area.',
        'CRITICAL: Git has NOT saved a new version yet!',
        'Selective staging allows you to craft clean, focused commits.',
      ],
      terminalDemo: {
        command: 'git add index.html',
        outputLines: [],
      },
      simulatorType: 'add',
      steps: [
        {
          id: 'add-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Modified File on Desk',
          description: 'You made changes to index.html in your code editor.',
          simpleExplanation: 'The file on your desk is modified, but Git\'s packing box is empty.',
          technicalExplanation: 'Working tree file index.html has modified mtime and hash differing from index.',
          whatGitChecks: 'File differences between disk and index.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['index.html modified on desk'],
          whyDidGitDoThat: 'Git does not automatically stage edits.',
        },
        {
          id: 'add-2-check',
          label: '2. Git Checks',
          phase: 'check',
          title: 'Git Inspects Target File',
          description: 'Git verifies the file exists and is not ignored by .gitignore.',
          simpleExplanation: 'Git checks the file to ensure it can be tracked.',
          technicalExplanation: 'Checks .gitignore patterns and file read permissions.',
          whatGitChecks: 'Permissions and ignore rules.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['File tracked'],
          whyDidGitDoThat: 'Ignored files should never enter the staging area accidentally.',
        },
        {
          id: 'add-3-compress',
          label: '3. Store Blob',
          phase: 'change',
          title: 'Git Compresses File Content',
          description: 'Git creates a blob object containing the exact content of index.html.',
          simpleExplanation: 'Git creates a digital backup copy of the file content.',
          technicalExplanation: 'Git writes a zlib-compressed blob object into .git/objects.',
          whatGitChecks: 'Hash computation.',
          whatGitChanges: 'New blob object written.',
          whatChangedBadges: ['Blob stored in DB'],
          whyDidGitDoThat: 'Git stores file versions as content-addressed blobs.',
        },
        {
          id: 'add-4-stage',
          label: '4. Update Index',
          phase: 'change',
          title: 'File Enters Staging Area',
          description: 'The index references the newly created blob object.',
          simpleExplanation: 'The file card physically moves into the Staging Area packing box!',
          technicalExplanation: '.git/index updated with filename, mode, and new blob hash.',
          whatGitChecks: 'Index integrity.',
          whatGitChanges: 'index.html staged.',
          whatChangedBadges: ['Staged: index.html'],
          whyDidGitDoThat: 'Staging lets you bundle multiple files together into a single logical commit.',
        },
        {
          id: 'add-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Staged, NOT Committed',
          description: 'NOTICE: Git has NOT saved a new commit yet. The change is merely prepared for snapshot.',
          simpleExplanation: 'The changes are packed in the box, waiting for you to run git commit.',
          technicalExplanation: 'Index holds the staged tree. HEAD commit remains unchanged.',
          whatGitChecks: 'Status verification.',
          whatGitChanges: 'Ready for commit.',
          whatChangedBadges: ['⚠️ Not a commit yet!'],
          whyDidGitDoThat: 'Staging is the deliberate preparation step before permanent sealing.',
        },
      ],
    },

    // 4. GIT STATUS
    'status': {
      id: 'status',
      command: 'git status',
      title: 'Checking Status',
      category: 'foundations',
      subtitle: 'See what Git sees across the 3 areas: Working Tree, Staging, and History.',
      mentalModelQuote: 'Ask Git: "What is the state of my project right now?"',
      keyTakeaways: [
        'git status is read-only and 100% safe to run anytime.',
        'Red text shows unstaged changes in the Working Tree.',
        'Green text shows staged changes in the Staging Area.',
        '"nothing to commit, working tree clean" means all files match HEAD.',
      ],
      terminalDemo: {
        command: 'git status',
        outputLines: [
          `On branch ${currentBranch}`,
          'Changes to be committed:',
          '  (use "git restore --staged <file>..." to unstage)',
          '	modified:   index.html',
          '',
          'Untracked files:',
          '  (use "git add <file>..." to include in what will be committed)',
          '	notes.txt',
        ],
      },
      steps: [
        {
          id: 'status-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'You Request Status',
          description: 'You run git status to gain situational awareness.',
          simpleExplanation: 'You ask Git to inspect your project and report what has changed.',
          technicalExplanation: 'Git prepares to compare Working Tree, Index, and HEAD commit.',
          whatGitChecks: 'File systems and indexes.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['Read-only inspection'],
          whyDidGitDoThat: 'Professional developers run git status before almost every action.',
        },
        {
          id: 'status-2-compare-tree',
          label: '2. Compare Disk & Index',
          phase: 'check',
          title: 'Git Compares Working Tree to Staging',
          description: 'Git scans files on disk and compares their hashes/timestamps to the index.',
          simpleExplanation: 'Git checks which files on your desk have been edited since they were staged.',
          technicalExplanation: 'Stat cache comparison detects modified, added, or deleted files on filesystem.',
          whatGitChecks: 'Working tree files against index.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['Unstaged modifications flagged'],
          whyDidGitDoThat: 'Git must identify uncommitted working edits.',
        },
        {
          id: 'status-3-compare-index',
          label: '3. Compare Index & HEAD',
          phase: 'check',
          title: 'Git Compares Staging to Last Commit',
          description: 'Git compares the index against the current HEAD commit tree.',
          simpleExplanation: 'Git checks what has been packed in the box that is not yet in history.',
          technicalExplanation: 'Tree diff between index and HEAD tree indicates "Changes to be committed".',
          whatGitChecks: 'Index against HEAD commit.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['Staged changes flagged'],
          whyDidGitDoThat: 'Shows what will enter the commit if you run git commit now.',
        },
        {
          id: 'status-4-complete',
          label: '4. Report',
          phase: 'complete',
          title: '3-Area Overview Displayed',
          description: 'Git displays a clear, color-coded summary of your project state.',
          simpleExplanation: 'You now know exactly what is on your desk and what is in the packing box.',
          technicalExplanation: 'Terminal displays branch status, upstream divergence, staged, unstaged, and untracked files.',
          whatGitChecks: 'Upstream branch sync status.',
          whatGitChanges: 'Terminal output printed.',
          whatChangedBadges: ['✓ Situational Awareness'],
          whyDidGitDoThat: 'Prevents mistakes by giving you total visibility into repository state.',
        },
      ],
    },

    // 5. GIT BRANCH & SWITCH
    'branch': {
      id: 'branch',
      command: 'git branch feature-login',
      title: 'Branches & Movable Pointers',
      category: 'branching',
      subtitle: 'Create a lightweight movable label pointing to a commit—not a folder copy!',
      mentalModelQuote: 'A branch is just a movable sticker pointing at a saved version.',
      keyTakeaways: [
        'A branch is NOT a copy of your project folder.',
        'It is a 41-byte text file storing the hash of a commit.',
        'Creating a branch is instantaneous and takes virtually zero disk space.',
        'HEAD tells Git which branch sticker you are currently standing on.',
      ],
      terminalDemo: {
        command: 'git branch feature-login',
        outputLines: [],
      },
      simulatorType: 'branch',
      steps: [
        {
          id: 'branch-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Single Line of History',
          description: 'You are on branch main pointing to your latest commit.',
          simpleExplanation: 'You have one active branch label (main) pointing to your newest commit.',
          technicalExplanation: `HEAD -> refs/heads/main -> ${headCommit}.`,
          whatGitChecks: 'Current HEAD position.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['main at C3'],
          whyDidGitDoThat: 'Branches always start from an existing commit or HEAD.',
        },
        {
          id: 'branch-2-create-pointer',
          label: '2. Create Pointer',
          phase: 'change',
          title: 'Branch Label Created',
          description: 'Git creates a new reference file pointing to the exact same commit as HEAD.',
          simpleExplanation: 'Git places a brand new sticker named "feature-login" onto the same commit!',
          technicalExplanation: `Writes .git/refs/heads/feature-login with content "${headCommit}".`,
          whatGitChecks: 'Valid branch name and non-collision.',
          whatGitChanges: 'New branch pointer created.',
          whatChangedBadges: ['New branch: feature-login'],
          whyDidGitDoThat: 'A branch is simply a reference file storing a 40-character commit ID.',
          prediction: {
            prompt: 'After running "git branch feature-login", which branch is HEAD currently pointing to?',
            options: [
              'Still on main (git branch creates the branch, but does NOT switch to it)',
              'Switched automatically to feature-login',
              'Detached from all branches',
              '🤔 I\'m not sure',
            ],
            correctIndex: 0,
            hint: 'To switch to the new branch, you must use git switch or git checkout.',
            explanation: 'git branch only creates the new pointer label! To start working on it, you run "git switch feature-login".',
          },
        },
        {
          id: 'branch-3-switch',
          label: '3. Switch HEAD',
          phase: 'change',
          title: 'Switching Context (git switch)',
          description: 'Running git switch feature-login moves the HEAD pointer to the new branch.',
          simpleExplanation: 'HEAD shifts from the main sticker to the feature-login sticker.',
          technicalExplanation: '.git/HEAD updated to "ref: refs/heads/feature-login".',
          whatGitChecks: 'Working directory clean check.',
          whatGitChanges: 'HEAD symbolic ref updated.',
          whatChangedBadges: ['HEAD -> feature-login'],
          whyDidGitDoThat: 'HEAD tells Git which branch should receive your next commit.',
        },
        {
          id: 'branch-4-complete',
          label: '4. Complete',
          phase: 'complete',
          title: 'Parallel Reality Ready',
          description: 'Any new commits you make will now advance feature-login, leaving main safely behind.',
          simpleExplanation: 'You can now experiment freely without breaking your main code.',
          technicalExplanation: 'Two independent reference pointers exist pointing at the commit graph.',
          whatGitChecks: 'Branch tips verified.',
          whatGitChanges: 'Ready for isolated commits.',
          whatChangedBadges: ['✓ Parallel Development'],
          whyDidGitDoThat: 'Branch isolation is the foundation of modern team software engineering.',
        },
      ],
    },

    // 6. GIT MERGE & FAST-FORWARD
    'merge': {
      id: 'merge',
      command: 'git merge feature-login',
      title: 'Merging Branches',
      category: 'branching',
      subtitle: 'Integrate two divergent lines of development into a combined history.',
      mentalModelQuote: 'A merge combines histories. It does not magically copy files.',
      keyTakeaways: [
        'Fast-Forward merge: If main has no new commits, main simply slides forward.',
        '3-Way Merge: If both branches have new commits, Git creates a new Merge Commit (M).',
        'The merge commit has two parent commits, joining their lineages.',
      ],
      terminalDemo: {
        command: 'git merge feature-login',
        outputLines: [
          'Updating 9b1c7a0..a3f2e1d',
          'Fast-forward',
          ' index.html | 5 +++++',
          ' 1 file changed, 5 insertions(+)',
        ],
      },
      simulatorType: 'merge',
      steps: [
        {
          id: 'merge-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Two Branch Histories',
          description: 'You are on main. Branch feature-login has commits you want to integrate.',
          simpleExplanation: 'Feature branch has completed work that you want to bring into main.',
          technicalExplanation: 'Local branch main at C2; feature branch at F2.',
          whatGitChecks: 'Current branch and target branch.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['main at C2', 'feature at F2'],
          whyDidGitDoThat: 'You must check out the receiving branch before running git merge.',
        },
        {
          id: 'merge-2-find-lca',
          label: '2. Common Ancestor',
          phase: 'check',
          title: 'Git Finds Lowest Common Ancestor',
          description: 'Git walks backwards through history to find the exact commit where the branches split.',
          simpleExplanation: 'Git finds the point in time where the two branches were last identical.',
          technicalExplanation: 'Computes Lowest Common Ancestor (LCA) using commit graph topological sort.',
          whatGitChecks: 'LCA commit node.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['Common Ancestor: C1'],
          whyDidGitDoThat: 'Finding the common ancestor enables Git to calculate true 3-way differences.',
        },
        {
          id: 'merge-3-decide',
          label: '3. Decide Strategy',
          phase: 'decide',
          title: 'Fast-Forward vs 3-Way Merge',
          description: 'Git determines whether history can fast-forward or requires a merge commit.',
          simpleExplanation: 'If main never added new commits, Git simply slides the main label forward!',
          technicalExplanation: 'If LCA == main, fast-forward is possible. Otherwise, 3-way merge is required.',
          whatGitChecks: 'Ancestry relationship.',
          whatGitChanges: 'Strategy chosen: Fast-Forward or 3-Way.',
          whatChangedBadges: ['Fast-Forward possible'],
          whyDidGitDoThat: 'Fast-forward preserves linear history when no divergence exists.',
        },
        {
          id: 'merge-4-converge',
          label: '4. Converge & Commit',
          phase: 'change',
          title: 'Histories Converged',
          description: 'Git creates a merge commit with 2 parents (or moves pointer in fast-forward).',
          simpleExplanation: 'The two streams of code are safely united into one history.',
          technicalExplanation: 'Merge commit M created with parents [C2, F2] or main pointer updated to F2.',
          whatGitChecks: 'Clean merge tree.',
          whatGitChanges: 'main points to merged tip.',
          whatChangedBadges: ['main updated to feature tip'],
          whyDidGitDoThat: 'Combining histories documents when and how feature code joined production.',
        },
        {
          id: 'merge-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Merged Successfully ✓',
          description: 'All changes from feature-login are now part of main.',
          simpleExplanation: 'Your main branch now includes all features cleanly.',
          technicalExplanation: 'Working tree updated to merged snapshot. Repository ready.',
          whatGitChecks: 'Final tree verification.',
          whatGitChanges: 'Ready for deployment.',
          whatChangedBadges: ['✓ In Sync with Feature'],
          whyDidGitDoThat: 'Both lines of development are now unified.',
        },
      ],
    },

    // 7. MERGE CONFLICTS
    'conflict': {
      id: 'conflict',
      command: 'git merge feature-redesign',
      title: 'Resolving Merge Conflicts',
      category: 'branching',
      subtitle: 'When two developers edit the same line, Git stops and asks human intelligence to choose.',
      mentalModelQuote: 'Git never guesses when human edits collide. It protects your code.',
      keyTakeaways: [
        'A conflict happens when two branches edit the exact same line of a file.',
        'Git pauses the merge and inserts conflict markers (<<<<<<<, =======, >>>>>>>).',
        'You choose: Keep Yours, Keep Theirs, or Combine Both.',
        'Stage the resolved file and commit to finalize the merge.',
      ],
      terminalDemo: {
        command: 'git merge feature-redesign',
        outputLines: [
          'Auto-merging index.html',
          'CONFLICT (content): Merge conflict in index.html',
          'Automatic merge failed; fix conflicts and then commit the result.',
        ],
      },
      simulatorType: 'conflict',
      steps: [
        {
          id: 'conflict-1-collision',
          label: '1. Collision',
          phase: 'start',
          title: 'Same Line Changed on Both Branches',
          description: 'You changed line 4 to "Welcome"; teammate changed line 4 to "Hello".',
          simpleExplanation: 'Two developers changed the exact same sentence differently.',
          technicalExplanation: 'Branch main and branch feature modified line 4 with divergent content.',
          whatGitChecks: 'Line-by-line diff against common ancestor.',
          whatGitChanges: 'Both branches advanced independently.',
          whatChangedBadges: ['Line 4 Collision'],
          whyDidGitDoThat: 'Git cannot know which developer\'s intent is correct without human review.',
        },
        {
          id: 'conflict-2-markers',
          label: '2. Conflict Markers',
          phase: 'change',
          title: 'Git Inserts Conflict Markers',
          description: 'Git writes <<<<<<< HEAD, =======, and >>>>>>> into the file.',
          simpleExplanation: 'Git marks the colliding lines directly inside the file so you can inspect both.',
          technicalExplanation: 'Working tree index.html written with 3-way conflict markers. Index holds unmerged stages 1, 2, 3.',
          whatGitChecks: 'Conflict bounds.',
          whatGitChanges: 'index.html contains conflict markers.',
          whatChangedBadges: ['Conflict Markers Placed'],
          whyDidGitDoThat: 'Markers allow standard text editors and IDEs to highlight conflicting choices.',
        },
        {
          id: 'conflict-3-resolve',
          label: '3. Human Choice',
          phase: 'decide',
          title: 'You Choose the Solution',
          description: 'You choose Accept Current (Yours), Accept Incoming (Theirs), or Combine Both.',
          simpleExplanation: 'You decide: "Let\'s combine them into: Welcome & Hello!"',
          technicalExplanation: 'Developer edits index.html and removes conflict marker delimiters.',
          whatGitChecks: 'Removal of markers.',
          whatGitChanges: 'File reflects intended merged code.',
          whatChangedBadges: ['Conflict Resolved on Disk'],
          whyDidGitDoThat: 'Human domain knowledge is required to integrate conflicting business logic.',
        },
        {
          id: 'conflict-4-stage',
          label: '4. Stage & Commit',
          phase: 'change',
          title: 'Mark Resolved (git add & commit)',
          description: 'Running git add index.html tells Git the conflict is solved.',
          simpleExplanation: 'Staging the file tells Git: "I solved the conflict. Proceed with the merge!"',
          technicalExplanation: 'git add resolves unmerged index stages into a clean staged blob.',
          whatGitChecks: 'Clean index.',
          whatGitChanges: 'Merge commit sealed.',
          whatChangedBadges: ['Merge Commit Completed'],
          whyDidGitDoThat: 'Staging is Git\'s universal signal that a file is verified and ready.',
        },
        {
          id: 'conflict-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Conflict Vanquished ✓',
          description: 'Merge is sealed. Your repository history now smoothly documents the resolution.',
          simpleExplanation: 'You resolved the conflict like a senior engineer!',
          technicalExplanation: 'Merge state cleared from .git/MERGE_HEAD. Repository clean.',
          whatGitChecks: 'Clean state.',
          whatGitChanges: 'Ready for push.',
          whatChangedBadges: ['✓ Peace Restored'],
          whyDidGitDoThat: 'Clear resolution ensures your build remains stable.',
        },
      ],
    },

    // 8. GIT REBASE
    'rebase': {
      id: 'rebase',
      command: 'git rebase main',
      title: 'Rebase: Clean Linear History',
      category: 'branching',
      subtitle: 'Replay your commits on top of a new base, creating new commit identities (D != D\').',
      mentalModelQuote: 'Rebase lifts your commits and replays them one by one on top of the newest work.',
      keyTakeaways: [
        'Rebase does NOT merely move a branch.',
        'It recreates your commits with different parent hashes (D becomes D\').',
        'Result is a clean, beautiful linear history without merge bubbles.',
        'Golden Rule: Never rebase commits that have already been pushed to a shared public branch!',
      ],
      terminalDemo: {
        command: 'git rebase main',
        outputLines: [
          'Successfully rebased and updated refs/heads/feature.',
        ],
      },
      simulatorType: 'rebase',
      steps: [
        {
          id: 'rebase-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Branches Diverged',
          description: 'Your feature branch started from C2, but main has advanced to C3.',
          simpleExplanation: 'You started your feature earlier, and teammate added C3 to main in the meantime.',
          technicalExplanation: 'feature branch points to D-E; main points to C3.',
          whatGitChecks: 'Divergence points.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['feature on old base C2'],
          whyDidGitDoThat: 'Rebase allows modern teams to avoid unnecessary merge commits for small features.',
        },
        {
          id: 'rebase-2-lift',
          label: '2. Lift Commits',
          phase: 'check',
          title: 'Feature Commits Lifted Aside',
          description: 'Git temporarily lifts commits D and E into a holding area.',
          simpleExplanation: 'Git sets your feature commits aside temporarily.',
          technicalExplanation: 'Git generates patch series for D and E in .git/rebase-apply.',
          whatGitChecks: 'Patch integrity.',
          whatGitChanges: 'feature commits detached.',
          whatChangedBadges: ['Commits D & E in holding queue'],
          whyDidGitDoThat: 'Git must move the branch base to C3 before replaying work.',
        },
        {
          id: 'rebase-3-reset-base',
          label: '3. Move Base to C3',
          phase: 'change',
          title: 'Base Moved to Tip of Main',
          description: 'Git resets the temporary working state to match commit C3.',
          simpleExplanation: 'Your branch base is now updated to the newest commit on main.',
          technicalExplanation: 'HEAD points temporarily to main tip (C3).',
          whatGitChecks: 'Target commit state.',
          whatGitChanges: 'Base synchronized with C3.',
          whatChangedBadges: ['Base updated to C3'],
          whyDidGitDoThat: 'Replay occurs on top of the target branch.',
        },
        {
          id: 'rebase-4-replay',
          label: '4. Replay Commits (D\' and E\')',
          phase: 'change',
          title: 'Commits Replayed with NEW Identities',
          description: 'Git applies D as D\' and E as E\'. NOTICE: D != D\' because parent hash is different!',
          simpleExplanation: 'Each commit is re-created one by one with a brand new ID fingerprint.',
          technicalExplanation: 'New commit D\' created with parent C3; new commit E\' created with parent D\'.',
          whatGitChecks: 'Patch application without conflict.',
          whatGitChanges: 'New commits D\' and E\' created in object DB.',
          whatChangedBadges: ['D → D\'', 'E → E\' (New Hashes)'],
          whyDidGitDoThat: 'Because parent hashes are part of the cryptographic commit ID, rebasing always changes commit hashes.',
        },
        {
          id: 'rebase-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Linear Timeline Achieved ✓',
          description: 'History is completely linear: A - B - C - D\' - E\'.',
          simpleExplanation: 'Your history looks as if you wrote your feature today on top of the latest code!',
          technicalExplanation: 'feature branch ref updated to E\'. Rebase state cleaned up.',
          whatGitChecks: 'Final linear lineage.',
          whatGitChanges: 'feature points to E\'.',
          whatChangedBadges: ['✓ Clean Linear Graph'],
          whyDidGitDoThat: 'Enables git bisect and clean code reviews across massive engineering organizations.',
        },
      ],
    },

    // 9. GIT RESET
    'reset': {
      id: 'reset',
      command: 'git reset --mixed HEAD~1',
      title: 'Undo with git reset',
      category: 'history',
      subtitle: 'Move current reference backwards and choose what happens to Staging and Working files.',
      mentalModelQuote: 'Rewind the timeline to an earlier milestone.',
      keyTakeaways: [
        '--soft: Moves HEAD backwards. Your changes remain staged in the packing box.',
        '--mixed (default): Moves HEAD backwards. Changes remain in your working files on desk.',
        '--hard: ⚠️ DESTRUCTIVE WORKING-TREE OPERATION. Working files and staging match target commit.',
        'Commits are not destroyed immediately; recoverable via git reflog!',
      ],
      terminalDemo: {
        command: 'git reset --mixed HEAD~1',
        outputLines: [
          'Unstaged changes after reset:',
          'M	index.html',
        ],
      },
      simulatorType: 'reset',
      steps: [
        {
          id: 'reset-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Timeline at C3',
          description: 'You made a commit C3 that you want to undo or re-craft.',
          simpleExplanation: 'You are standing at commit C3, but you want to step back to C2.',
          technicalExplanation: 'HEAD -> main -> C3. Index and working tree are clean.',
          whatGitChecks: 'Target commit validity (HEAD~1 = C2).',
          whatGitChanges: 'None.',
          whatChangedBadges: ['At C3'],
          whyDidGitDoThat: 'Reset is the primary tool for undoing local, unpushed commits.',
        },
        {
          id: 'reset-2-choose-mode',
          label: '2. Choose Mode',
          phase: 'decide',
          title: 'Select Reset Mode (--soft, --mixed, --hard)',
          description: 'Compare the three modes:\n--soft: Keeps staged\n--mixed: Keeps on desk\n--hard: Overwrites disk',
          simpleExplanation: 'Choose whether you want your code kept in the box, kept on your desk, or wiped.',
          technicalExplanation: 'Soft modifies only HEAD. Mixed modifies HEAD + Index. Hard modifies HEAD + Index + Working Tree.',
          whatGitChecks: 'Selected mode flags.',
          whatGitChanges: 'Strategy chosen.',
          whatChangedBadges: ['Mode: --mixed (Safe Desk)'],
          whyDidGitDoThat: 'Different undo needs require different levels of file preservation.',
        },
        {
          id: 'reset-3-move-head',
          label: '3. Move HEAD & Branch',
          phase: 'change',
          title: 'Branch Reference Moves to C2',
          description: 'The branch label and HEAD move backwards from C3 to C2.',
          simpleExplanation: 'Git rewinds the branch sticker backwards to commit C2.',
          technicalExplanation: 'refs/heads/main updated to C2 hash. C3 is now unreferenced by current branch.',
          whatGitChecks: 'Target commit object.',
          whatGitChanges: 'main -> C2.',
          whatChangedBadges: ['main rewound to C2'],
          whyDidGitDoThat: 'Moving the branch pointer rewinds the project history.',
        },
        {
          id: 'reset-4-adjust-files',
          label: '4. Adjust Working State',
          phase: 'change',
          title: 'Files Preserved on Desk',
          description: 'In --mixed mode, C3\'s changes are unstaged and placed safely on your desk.',
          simpleExplanation: 'Your code is still right in front of you in your editor, ready to be fixed!',
          technicalExplanation: 'Index reset to match C2 tree. Working tree remains untouched with modified files.',
          whatGitChecks: 'Working tree safety.',
          whatGitChanges: 'index.html modified on desk.',
          whatChangedBadges: ['Code safe on desk'],
          whyDidGitDoThat: 'Safe reset prevents accidental work loss while rewinding commit history.',
        },
        {
          id: 'reset-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Reset Completed ✓',
          description: 'You stepped back in time without losing your work. (C3 is still in git reflog if needed!)',
          simpleExplanation: 'You can now re-edit your code and make a cleaner commit.',
          technicalExplanation: 'Reflog records HEAD@{1}: reset: moving to HEAD~1. Repository ready.',
          whatGitChecks: 'Reflog updated.',
          whatGitChanges: 'Ready for new edits.',
          whatChangedBadges: ['✓ Rewound Safely'],
          whyDidGitDoThat: 'Gives developers total freedom to experiment without fear of permanent error.',
        },
      ],
    },

    // 10. GIT STASH
    'stash': {
      id: 'stash',
      command: 'git stash',
      title: 'Git Stash: The Emergency Drawer',
      category: 'history',
      subtitle: 'Temporarily shelve dirty working files into a drawer, leaving your desk clean.',
      mentalModelQuote: 'Sweep your unfinished desk work into a drawer so you can switch tasks cleanly.',
      keyTakeaways: [
        'git stash takes dirty working files and staged files and saves them in a stack.',
        'Working tree returns to a clean state matching HEAD.',
        'git stash pop restores your shelved changes and removes them from the drawer.',
        'Perfect when you need to switch branches urgently to fix a bug.',
      ],
      terminalDemo: {
        command: 'git stash',
        outputLines: [
          `Saved working directory and index state WIP on ${currentBranch}: ${headCommit} Update homepage`,
        ],
      },
      simulatorType: 'stash',
      steps: [
        {
          id: 'stash-1-start',
          label: '1. Start',
          phase: 'start',
          title: 'Unfinished Edits on Desk',
          description: 'You are halfway through a feature, but an urgent bug requires you to switch branches.',
          simpleExplanation: 'Your desk is messy with unfinished edits. Git won\'t let you switch branches cleanly.',
          technicalExplanation: 'Dirty working tree index.html and style.css differing from HEAD.',
          whatGitChecks: 'Dirty files on disk.',
          whatGitChanges: 'None.',
          whatChangedBadges: ['2 files dirty'],
          whyDidGitDoThat: 'Switching branches with dirty files could cause file overwrites.',
        },
        {
          id: 'stash-2-open-drawer',
          label: '2. Open Drawer',
          phase: 'change',
          title: 'Shelve Changes in Stash Stack',
          description: 'Git creates special stash commit objects storing your index and working tree.',
          simpleExplanation: 'The stash drawer slides open and your unfinished files slide inside!',
          technicalExplanation: 'Git creates commit objects for index state and working tree state, saved in refs/stash.',
          whatGitChecks: 'File differences.',
          whatGitChanges: 'Changes placed into stash@{0}.',
          whatChangedBadges: ['Stashed into drawer'],
          whyDidGitDoThat: 'Stash commits preserve both staged and unstaged edits independently.',
        },
        {
          id: 'stash-3-clean-desk',
          label: '3. Clean Desk',
          phase: 'change',
          title: 'Working Tree Becomes Clean',
          description: 'Git resets your working tree files to match the clean HEAD commit.',
          simpleExplanation: 'Your desk is instantly spotless! You can now switch branches safely.',
          technicalExplanation: 'Working directory files reverted to HEAD tree state.',
          whatGitChecks: 'Disk clean state.',
          whatGitChanges: 'Working files clean.',
          whatChangedBadges: ['Working Tree Clean ✓'],
          whyDidGitDoThat: 'A clean desk allows you to pull, checkout other branches, or hotfix safely.',
        },
        {
          id: 'stash-4-pop',
          label: '4. Pop Changes',
          phase: 'change',
          title: 'Restore Work with git stash pop',
          description: 'When you return, running git stash pop slides the drawer open and restores your work.',
          simpleExplanation: 'Your unfinished work slides back onto your desk exactly as you left it!',
          technicalExplanation: 'Stash commit applied back to working tree; stash@{0} dropped from stack.',
          whatGitChecks: 'Merge safety.',
          whatGitChanges: 'Dirty files restored; stash stack decremented.',
          whatChangedBadges: ['Work Restored to Desk'],
          whyDidGitDoThat: 'Ensures zero wasted time context switching.',
        },
        {
          id: 'stash-5-complete',
          label: '5. Complete',
          phase: 'complete',
          title: 'Stash Mastered ✓',
          description: 'You handled an urgent interruption without creating half-baked commits.',
          simpleExplanation: 'Your work is back on your desk, ready for you to finish.',
          technicalExplanation: 'Repository in identical state prior to stash interruption.',
          whatGitChecks: 'State verified.',
          whatGitChanges: 'Ready to continue.',
          whatChangedBadges: ['✓ Resumed Effortlessly'],
          whyDidGitDoThat: 'Stash is one of the most beloved productivity tools in professional Git.',
        },
      ],
    },
  };

  return stories[commandId] || stories['push'];
}
